# Generated by Django 4.0.5 on 2022-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='hashview',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
