# Generated by Django 4.0.5 on 2022-06-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_todo_hashview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='hashview',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
